#!/bin/bash

page_stx="stx"
wget https://git.openstack.org/cgit/?q=stx -O $page_stx

repos=$(grep "openstack/stx-" $page_stx | awk -F 'title=' '{print $2}' | awk -F "'" '{print $2}' | awk -F "/" '{print $2}' )

for repo in $repos; do
	git clone https://git.openstack.org/openstack/$repo && (cd $repo && curl -kLo `git rev-parse --git-dir`/hooks/commit-msg https://git.openstack.org/tools/hooks/commit-msg; chmod +x `git rev-parse --git-dir`/hooks/commit-msg)
done

rm $page_stx

mkdir repos
mv stx-* repos
